[package]
name = "verdi-input"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
verdi-math = { path = "../verdi-math" }
rlua = "0.19.4"
glium = "*"
egui_glium = "0.19.0"