[package]
name = "verdi-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
verdi-window = { path = "../verdi-window" }
verdi-graphics = { path = "../verdi-graphics" }
glium = "*"
rlua = "0.19.4"
lazy_static = "1.4"
thiserror = "1.0.34"