[package]
name = "verdi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/*"]

[dependencies]
verdi-internal = { path = "crates/verdi-internal" }
lazy_static = "1.4"