[package]
name = "verdi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
verdi-renderer = { path = "crates/verdi-renderer" }
verdi-window = { path = "crates/verdi-window" }