[package]
name = "verdi-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
verdi-utils = { path = "../verdi-utils" }
rlua = "0.19.4"
thiserror = "1.0.34"
notify = "5.0.0"